---
- name: Install node and npm
  hosts: all
  tasks:
    - name: Udate apt repo and cache
#      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 где то ошибка
      apt: update_cache=yes force_apt_get=yes
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: all
  tasks:
    - name: Create linux user
      user:
        name: tehuser
        comment: Tehuser Admin
        group: admin

- name: Deploy nodejs app
  hosts: all
# эти две строки для настройки пользователя, без них будет рут
  become: True
  become_user: tehuser
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: ./../distr/node-example.tgz
        dest: /home/tehuser
    - name: Install dependencies
      npm:
        path: /home/tehuser/react-nodejs-example-master/my-app
    - name: Start the application
      command:
#        в таком виде работает, но ansible зависает, потому что не сервис а процесс, лечится (нет) async and poll
        chdir: /home/tehuser/react-nodejs-example-master/my-app
        cmd: npm start
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout}}



#  Так можно, но это избыточно
#    - name: Copy nodejs foder to a server
#      copy:
#        src: ./../distr/node-example.tgz
#        dest: /root/app-1.0.0.tgz
#    - name: Unpack the nodejs file
#      unarchive:
#        src: /root/app-1.0.0.tgz
#        dest: /root/
##       указыаем, что все это проделывается на удаленной машине, иначе он будет пытаться распаковать с локальной
#        remote_src: yes

