#три дефиса разделяют разные задачи
---
# name может быть произвольным
- name: Configure nginx web server
# беретсф из файла hosts
  hosts: webserver
# задачи которые мы будем выполнять, используем для этого список
  tasks:
  - name: uninstall nginix server
# это уже модуль, УДАЛЯЕМ nginx
    apt:
      name: nginx
      state: absent
# это уже следующая задача, используем модуль service, и запускаем nginx
  - name: STOP nginx server
    service:
      name: nginx
      state: stopped